version: "1.0"
services: 
 mysql:
  image: mysql:latest
  restart: always
  container_name: Full-2020-94877
  ports:
   - "3306:3306"
  networks:
   Bridge-Zadanie-1:
    ipv4_address: 10.0.10.3
  environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pfswcho"
      MYSQL_USER: "dkornas"
      MYSQL_PASSWORD: "dominika"
 java:
  image: kornasiowa/pfswcho_docker:latest
  stdin_open: true
  tty: true
  container_name: Aplikacja
  depends_on:
   - mysql
  networks:
   - Bridge-Zadanie-1
networks:
 Bridge-Zadanie-1:
  driver: bridge
  ipam:
   config:
    - subnet: 10.0.10.0/24